name: ESP32-S3 Firmware Build

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build esp32s3o-finware (IDF v6.0.1 · esp32s3)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-${{ github.sha }}
          restore-keys: ccache-

      - name: Build con ESP-IDF v6.0.1
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0.1
          target: esp32s3
          path: '.'
          command: export CCACHE_DIR=$PWD/.ccache && idf.py --ccache build

      - name: Reunir los 3 .bin
        run: |
          mkdir -p finware
          cp build/bootloader/bootloader.bin finware/
          cp build/partition_table/partition-table.bin finware/
          cp build/esp32s3o-finware.bin finware/

      - name: Upload finware
        uses: actions/upload-artifact@v4
        with:
          name: finware
          path: finware/
          if-no-files-found: error
          retention-days: 30
